; ===================== MEASURES 1 =====================


[mGMail1_Subject]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail1_Sender]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail1_EmailDate]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail1_Snipet]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail


[mGMail1_Link]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail



; ===================== MEASURES 2 =====================


[mGMail2_Subject]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail2_Sender]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail2_EmailDate]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail2_Snipet]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail


[mGMail2_Link]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail



