; ===================== MEASURES {0} =====================


[mGMail{0}_Subject]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail{0}_Sender]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail{0}_EmailDate]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail

[mGMail{0}_Snipet]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail


[mGMail{0}_Link]
Measure=Plugin
Plugin=RainGoo.dll
ParentName=mGMail



